### ISSUE TITLE
[need good english] improve spelling readme.md and in-using.md file. 

### ISSUE THREAD

**Issue by MairwunNx** [ProjectEssentials/ProjectEssentials-Permissions#12]
Need to improve the spelling of the text in the documentation files (`readme.md` and `documentation/in-using.md`)

I speak technical English, not native, so I make many semantic errors in the text. I will be grateful if you improve my documentation text, I am sure there are problem areas.

If you have any problems - talk with me, I will let you know what I meant. Also, if you want, you can write to me why your option is correct, I will be glad.

**Comment by deannadoestech** [comment]
Would be happy to take this on! I'm a technical writer looking to gain more experience w/open source projects

**Comment by MairwunNx** [comment]
@deannadoestech thanks, good luck, happy hacking! 🍀

**Comment by abhiroopwastaken** [comment]
@MairwunNx I would also be happy to Contribute. Shall I?

**Comment by MairwunNx** [comment]
@abhiroopwastaken of course, thanks for contributing! 🥰

**Comment by Aircoookie** [comment]
@MairwunNx just opened a PR with a few changes to the wording 😄

**Comment by MairwunNx** [comment]
@Aircoookie awesome! I review it today. 🥰
