### ISSUE TITLE
Permissions listings in-game

### ISSUE THREAD

**Issue by seisatsu** [ProjectEssentials/ProjectEssentials-Permissions#21]
Currently there does not appear to be any way to see a list of permissions groups, the list of nodes within the groups, or the members of a group, etc. without reading the permissions file on the server. Commands for listing existing permissions in-game would be very useful.

**Comment by MairwunNx** [comment]
@seisatsu I completely agree, this is very useful, it will be implemented in the next minor version `v1.14.4-1.3.0`. Thanks 🥰! What name of command do you expect for a list of rights and what message format do you expect? I will be glad if you describe the task in more detail, this will allow me to complete it in more detail. 😉

**Comment by seisatsu** [comment]
There's probably a few ways it could be done. Here's some ideas that work with how the commands are written currently.

`/permissions group [name]` with no extra arguments lists the group's members and nodes.
`/permissions user [name]` with no extra arguments lists the user's groups and nodes.
`/permissions list` lists the groups.

**Comment by Yoosk** [comment]
In case of permissions, do we have ability to restrict anyone from using given item?

**Comment by MairwunNx** [comment]
@Yoosk 

Yes, you can, if you write your own handler for using items, but if you want built-in processing for using items, I will try to add this only in the next version.

If things are registered in your mod, you can override onUse method or something like that where to check for a certain permission.

It should look something like this (if use kotlin)
```kotlin
override fun OnItemUse(event: ...) {
    // Item use will be canceled if player don't have certain permission.
    event.cancel = !PermissionsAPI.hasPermission(...)
    // Send message "You don't have permissions for use it item ...".
}
```

If this answer is not enough for you or you want to ask more, create a separate issue, it will be more convenient.

**Comment by MairwunNx** [comment]
### *Not related to this issue*

@Yoosk resolved in `2.0.0-SNAPSHOT.1+MC-1.14.4` and will included in `2.0.0-RC.1+MC-1.14.4` (Release Candidate) for testing this feature.

Usage example will added to documentation before pushing Release Candidate version to project releases. Thanks.

*Currently changes in local git and no able for testing.*

**Comment by MairwunNx** [comment]
@seisatsu I started work on this, as soon as I have news for you, I will update the labels in this issue.

**Comment by MairwunNx** [comment]
Implemented in https://github.com/ProjectEssentials/ProjectEssentials-Permissions/commit/619b728a2d08a6c09ebb45d1f70a246df913ce8c, but this issue will closed when will implemented listing for group too.

**Comment by MairwunNx** [comment]
Implemented in https://github.com/ProjectEssentials/ProjectEssentials-Permissions/commit/4af6aee3153063ebf82bd6e8be4ec900462fdb4d, but this changes need test and code will cleaned in Release.

**Comment by MairwunNx** [comment]
This issue will closed after tests by me or someone other.

**Comment by MairwunNx** [comment]
Resolved in https://github.com/ProjectEssentials/ProjectEssentials-Permissions/commit/8cf6a50309480bceeabf99661424f3221a67754b commit and tested on server and client. Feature included in `SNAPSHOT.2`.
