### ISSUE TITLE
Not possible to use wildcards in permissions nodes

### ISSUE THREAD

**Issue by seisatsu** [ProjectEssentials/ProjectEssentials-Permissions#22]
Currently it is impossible to assign permissions nodes containing wildcards using in-game commands.

Example: `/permission group worldedit set worldedit.*` gives `Expected whitespace to end one argument, but found trailing data`.

**Comment by MairwunNx** [comment]
@seisatsu `/permissions group worldedit set "worldedit.*"`

**Comment by seisatsu** [comment]
Ah, that works. Thanks.
