### ISSUE TITLE
Crash on World Creation

### ISSUE THREAD

**Issue by dreckz** [ProjectEssentials/ProjectEssentials-Permissions#23]
### Describe the bug
> - When you attempt to create a world, the game crashes

This is with PE:Core, PE:Backup, PE:Chat, and PE:Perms

### Steps to reproduce the behavior
> - 1. Create world
> - 2. Allow to generate
> - Crashes

### Expected behavior
> - Normally the world should work properly

### Screenshots
> - N/A

### Environment information
> - Project Essentials Permissions version: [e.g. v1.0.1]
> - Project Essentials Core version: [e.g. v1.1.0]
> - Project Essentials Modules version: [Backup - v1.0.1; Perms - v1.0.1]
> - Minecraft / Forge version: [e.g. 1.15.2 / 31.1.25]

### Additional context
> - N/A

### Log files. (latest.log and debug.log file in attachment)
[crash-2020-03-21_04.46.07-server.txt](https://github.com/ProjectEssentials/ProjectEssentials-Permissions/files/4362678/crash-2020-03-21_04.46.07-server.txt)

**Comment by MairwunNx** [comment]
### ✔ Resolved in `1.15.2-1.0.2` and `1.14.4-1.2.2` permissions module.

#### @dreckz, thanks for bug report. 🥰
