### ISSUE TITLE
Being OP should bypass all permissions. 

### ISSUE THREAD

**Issue by andylmfao** [ProjectEssentials/ProjectEssentials-Permissions#30]
Title says it, very annoying to have to work with console and nodes since there isn't even a clear representation of all nodes and what their names are. Plus being added to the "owner" group does absolutely nothing and doesn't even work when being added to it.

**Comment by hujle** [comment]
/op name
then restart the server

**Comment by andylmfao** [comment]
"native.command.restricted" 

even when i MANUALLY add permission nodes in the config file, nothing happens, says the same error. Also when i try to reload it just goes "An unexpected error occurred while trying to do that command"

**Comment by hujle** [comment]
op yourself through the console since you have access to it

**Comment by andylmfao** [comment]
![image](https://user-images.githubusercontent.com/63781863/80915219-2fadad00-8d51-11ea-89aa-9acc65c036fa.png)

Yep that's what i did, op'd myself, restarted, still can't do anything

**Comment by MairwunNx** [comment]
@andylmfao, can you drop `permissions.json` file here?

**Comment by andylmfao** [comment]
https://pastebin.com/wTcnRN4d

here you go.

My goal is to have me (andylmfao) have all permissions and be "owner" group, and "default" to have what they have as default plus /tp, and /toggledownfall

**Comment by MairwunNx** [comment]
@andylmfao try add permission `*` to your permissions. It's works?

**Comment by MairwunNx** [comment]
Haha, @andylmfao, man. Your nick is wrong.

![image](https://user-images.githubusercontent.com/39625750/80915468-36412200-8d5b-11ea-90a7-4b5f4eef21e2.png)
![image](https://user-images.githubusercontent.com/39625750/80915472-37724f00-8d5b-11ea-9759-a3ae21b6f346.png)

**Comment by andylmfao** [comment]
Welp, I'm terribly sorry for wasting everyones time with my stupidity, however there still is the bug about the mod reload.

**Comment by hujle** [comment]
made a typo in your own nickname, and put the group name into the perms, when you could just put "*". absolute madman.
 you could even dont touch permissions config and everything would working fine. at least it works for me.

**Comment by andylmfao** [comment]
Yeah true, terribly sorry again.

**Comment by MairwunNx** [comment]
@andylmfao 

If this problem resolved for you, you can close this issue.
If you have one more problem then create this issue with new problem context.

#### Good luck 🍀!
