### ISSUE TITLE
Groups not setting on perm user commadn

### ISSUE THREAD

**Issue by Norava** [ProjectEssentials/ProjectEssentials-Permissions#34]
### Describe the bug
> - When using `perm user [Username] set [Group name] `a permission node with whatever string populates into the users Permissions section rather than changing their group

### Steps to reproduce the behavior
Run `perm user [Username] set [Already defined group name]`

### Expected behavior
A user to have their group changed

### Screenshots
Not a screenshot but here's my Permissions.json. The exact command I'm running is `perm user Norava set Eldritch`
`{
    "groups": [
        {
            "name": "Anomaly",
            "isDefault": true,
            "permissions": [
                "native.help",
                "native.list",
                "native.me",
                "native.message",
                "native.teammsg",
                "native.tell",
                "native.trigger",
                "native.w",
                "native.event.modifyworld",
                "ess.warp",
                "ess.warp.set",
                "ess.warp.remove",
                "ess.chat",
                "ess.chat.mention.all",
                "ess.home",
                "ess.home.set",
                "ess.home.remove",
                "ess.spawn",
                "ess.afk",
                "ess.sendpos",
                "ess.tpaccept",
                "ess.tpdeny",
                "ess.tptoggle",
                "ess.tpaall",
                "ess.tpacancel",
                "ess.tpa",
                "ess.tpahere"
            ],
            "inheritFrom": [
            ]
        },
        {
            "name": "Star",
            "isDefault": false,
            "permissions": [
                "native.tp",
                "ess.suicide"
            ],
            "inheritFrom": [
                "Anomaly"
            ]
        },
        {
            "name": "Voidling",
            "isDefault": false,
            "permissions": [
                "ess.top"
            ],
            "inheritFrom": [
                "Star"
            ]
        },
        {
            "name": "Eldritch",
            "isDefault": false,
            "permissions": [
                "*"
            ],
            "inheritFrom": [
                "Voidling"
            ]
        }
    ],
    "users": [
        {
            "nickname": "*",
            "group": "default",
            "permissions": [
            ]
        },
        {
            "nickname": "#server",
            "group": "owner",
            "permissions": [
            ]
        },
        {
            "nickname": "OniNikku",
            "group": "Eldritch",
            "permissions": [
                ""
            ]
        },
        {
            "nickname": "007Deer",
            "group": "Voidling",
            "permissions": [
                ""
            ]
        },
        {
            "nickname": "Norava",
            "group": "Eldritch",
            "permissions": [
                ""

            ]
        }
    ]
}`

### Environment information
> - Project Essentials Permissions version:1.15.2-1.0.2
> - Project Essentials Core version: 1.15.2-1.1.0
> - Project Essentials Cooldown version: 1.15.2-1.0.2
> - Project Essentials Modules version: 1.15.2-1.1.0
> - Minecraft / Forge version: 1.15.2-31.2.20

### Additional context
> - Add any other context about the problem here.

**Comment by MairwunNx** [comment]
Hello! @Norava ,

Sorry, I not support the 1.x family now, use the 2.x project essentials modules. 👍
