### ISSUE TITLE
Update some dependencies (e.g `kotlinx.serialization`) and gradle wrapper.

### ISSUE THREAD

**Issue by MairwunNx** [ProjectEssentials/ProjectEssentials-Permissions#5]
## Just needed update dependencies in `gradle.properties` file.

I think already exist new version of `kotlinx.serialization`, `dokka plugin`, `gradle wrapper`.

Just replace version numbers in `gradle.properties` file.
Gradle wrapper version can be changed in `gradle/wrapper/gradle-wrapper.properties`.

New version you can find in https://github.com/search, just type repository name in search bar, and see releases / docs of installation.

**Comment by luckymurari** [comment]
If you are busy I can do it.

**Comment by MairwunNx** [comment]
@luckymurari of course, good luck 🍀 and happy hacking 🐱‍💻!

**Comment by luckymurari** [comment]
Thank you. I have submitted a PR. Please merge
