### ISSUE TITLE
Just change base project package to normal package name.

### ISSUE THREAD

**Issue by MairwunNx** [ProjectEssentials/ProjectEssentials-Permissions#6]
## Need change project package to normal name.

Current package name: `com.mairwunnx.projectessentialspermissions`
Needed package name: `com.mairwunnx.projectessentials.permissions`

Rename **ONLY WITH REFACTORING FUNCTION IN `IntellijIDEA`!!!**

No more. This is a very simple task, but I'm too lazy to do this, so if you want to make your first PR or maybe not the first, then try :)

**Comment by remikeophila** [comment]
going for it

**Comment by MairwunNx** [comment]
## ✔ Resolved in #7
