### ISSUE TITLE
Need to write project version changelog into file `changelog.md`

### ISSUE THREAD

**Issue by MairwunNx** [ProjectEssentials/ProjectEssentials-Permissions#8]
## I'm so lazy for it task, because, i create it issue for newbies on github or not newbies :) 

You need just create `changelog.md` file and make it beautiful, changes you can take in file `update.json`

In json object with name `1.14.4` stores all versions and changes as string, just you need to rewrite all changes for each version to a `changelog.md` file. And do not forget. **Make it beautiful** :)

Good luck! 🎉🥰

**Comment by drigio** [comment]
Hey @MairwunNx  I would like to work on this :)

**Comment by MairwunNx** [comment]
@drigio no problem, good luck! 🍀
